### ISSUE TITLE
Addition of Blog section required.

### ISSUE THREAD

**Issue by Zeeshan-2k1** [hnccbits/contest.hnccbits.com#14] opened 2020-09-25 05:48 UTC
A blog section is to be added before footer. Can be made by using [Card](https://material-ui.com/components/cards/) of Material-UI

**Comment by AnandBIT** [comment] 2020-09-27 05:16
I've added the blog section
Check, if the issue is solved, then please close this issue

**Comment by AnandBIT** [comment] 2020-09-27 05:17
I've added the blog section
Please check @Zeeshan-2k1 @suraj-sloth 
If the issue is solved, then please close this issue

**Comment by Zeeshan-2k1** [comment] 2020-09-27 06:28
Nice @AnandBIT. Working good.

**Comment by Zeeshan-2k1** [comment] 2020-09-28 09:13
@suraj-sloth Content needed here and check for responisveness.

**Closed** 2020-09-30 16:32 UTC
Labels: good first issue, help wanted
